CREATE TABLE teams (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source_team_id VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  short_name VARCHAR(40) NOT NULL,
  division VARCHAR(16) NOT NULL,
  conference VARCHAR(32) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE games (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source_game_id VARCHAR(64) NOT NULL UNIQUE,
  season VARCHAR(16) NOT NULL,
  game_date DATE NOT NULL,
  status VARCHAR(24) NOT NULL,
  home_team_id INT UNSIGNED NOT NULL,
  away_team_id INT UNSIGNED NOT NULL,
  home_score SMALLINT UNSIGNED NULL,
  away_score SMALLINT UNSIGNED NULL,
  venue VARCHAR(160) NULL,
  raw_payload JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_games_date (game_date),
  INDEX idx_games_season (season),
  CONSTRAINT fk_games_home_team FOREIGN KEY (home_team_id) REFERENCES teams(id),
  CONSTRAINT fk_games_away_team FOREIGN KEY (away_team_id) REFERENCES teams(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE team_daily_records (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  team_id INT UNSIGNED NOT NULL,
  season VARCHAR(16) NOT NULL,
  record_date DATE NOT NULL,
  wins SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  losses SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  points_for INT NOT NULL DEFAULT 0,
  points_against INT NOT NULL DEFAULT 0,
  home_wins SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  home_losses SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  away_wins SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  away_losses SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_team_daily (team_id, season, record_date),
  CONSTRAINT fk_records_team FOREIGN KEY (team_id) REFERENCES teams(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
